### ISSUE TITLE
Unable to view website

### ISSUE THREAD

**Issue by MarcAnthonyPhotography** [yTakkar/Instagram-clone#7]
I created a database and named my database eventpix. I imported the database just fine. I replaced all references of the database to host=localhost;dbname=eventpix;charset=utf8mb4', 'myusername', 'my password'. I changed the root path from /faiyaz/Instagram to /eventpix so my site is www.mysite.com/eventpix. Any thoughts on why when I go to the root site (ie. www.mysite.com/eventpix) it is blank. Your instructions seemed straight forward. I should note. My website is https. Not sure if that matters. I also checked my error log and I get this. PHP Parse error:  syntax error, unexpected '$noti' (T_VARIABLE) in /home/ipixsocial/public_html/eventpix/config/class/post_comment.class.php on line 399

**Comment by yTakkar** [comment]
Not sure on why it's not working for u, but i'll go through  the instructions again. Give me your email and l'll send you screenshots of every step.

**Comment by MarcAnthonyPhotography** [comment]
Thank you. My email is marcanthonyphotography@gmail.com

**Comment by githubertus** [comment]
missing semicolon (;) end of line 397

**Comment by MarcAnthonyPhotography** [comment]
Thank you. I got that to work but now when I try to create an account there is an issue. I am able to create an account and it stores the info properly in the database but the account freezes when you try and login. Here's my website. https://ipixsocial.com/eventpix

**Comment by yTakkar** [comment]
@MarcAnthonyPhotography  i'll check!!

**Comment by yTakkar** [comment]
@githubertus  which file??

**Comment by githubertus** [comment]
config/class/post_comment.class.php

**Comment by yTakkar** [comment]
Thnx @githubertus i'll fix and commit it!

**Comment by yTakkar** [comment]
Fixed it!!
Mistakenly wrote `*****` instead of `GMAIL_PASSWORD` in `login.class.php`.
Make sure you are using `gmail` account.
Also Google sometimes blocks sent emails, which they did:
![snap 2017-06-28 at 04 29 21](https://user-images.githubusercontent.com/24929880/27613664-71083962-5bba-11e7-88ce-f0e978640161.png)
**Pull for these new changes**

**Comment by MarcAnthonyPhotography** [comment]
Still having issues. It freezes when I try to login. The user info is stored in the DB but I can't login or do anything. I attached a pdf version of the php scripts. I commented out my password with **** but can you tell me if this is correct? Also, any reference to database I have $db = new
PDO('mysql:host=localhost;dbname=eventpixdatabase;charset=utf8mb4',
'eventpixadmin', '****');  (**** is my password).

[forgot.pdf](https://github.com/yTakkar/Instagram-clone/files/1112954/forgot.pdf)
[login.pdf](https://github.com/yTakkar/Instagram-clone/files/1112955/login.pdf)

**Comment by wazowski78** [comment]
Check the php version. 

Enviado desde mi iPhone

**Comment by MarcAnthonyPhotography** [comment]
It's php5.6. Are they any special php settings I need to enable? 

Cordially,
Marc A. Matteo
iSIT Kiosk
www.isitkiosk.com
856.981.3209

**Comment by MarcAnthonyPhotography** [comment]
I tried setting to php 5.5 and 5.4. It still freezes on logging in. I'm stumped.

**Comment by yTakkar** [comment]
I followed all the steps again to check if it works. As I was following I noticed a bug.
In point no. 4 
`$db = new PDO('mysql:host=host;dbname=instagram;charset=utf8mb4', 'root', 'user')` 
is wrong, correct one is 
`$db = new PDO('mysql:host=host;dbname=instagram;charset=utf8mb4', 'user', 'password')`.
I've commited it, here's the link [commit](https://github.com/yTakkar/Instagram-clone/commit/7e320d869541a646fe06c39760039018bbfdc2e9)

**Comment by githubertus** [comment]
@MarcAnthonyPhotography 
If the package doesn't work, there must be errors being logged: 
- php errors in your webservers log file
- javascript errors in your browser's development console

@yTakkar 
Actually there's a good chance for making typos with the endless number of files you have to adapt to your own environment. It would be of great help having just one php file with the db connector to be included where necessary instead of having the same code again and again. The same is true for the path setting.

**Comment by yTakkar** [comment]
@githubertus I thought about it long ago, but never got time as I was always busy with some projects. But now thinking to do it finally.

**Comment by yTakkar** [comment]
@githubertus, did it!!

**Comment by githubertus** [comment]
Well done!
I think this will help you getting a lot more installations. :)
It's likely you'll get even more after making the whole project responsive via bootstrap or something like that - my main interest was your elegant ajax part, to be honest.

**Comment by yTakkar** [comment]
@githubertus thnx a lot!!
